export const Login_API = "https://cp-blog.onrender.com/api/login"
export const Register_API = "https://cp-blog.onrender.com/api/user"
export const post_API = "https://cp-blog.onrender.com/api/post"
export const profile_APi = "https://cp-blog.onrender.com/api/user/me"
export const allPost_API = "https://cp-blog.onrender.com/api/post/user"
export const sample_image = "https://marketinginsidergroup.com/wp-content/uploads/2023/09/shutterstock_234456937-scaled-1.jpg"