export const Login_API = "https://cp-blog.onrender.com/api/login"
export const Register_API = "https://cp-blog.onrender.com/api/user"
export const post_API = "https://cp-blog.onrender.com/api/post"
export const profile_APi = "https://cp-blog.onrender.com/api/user/me"
export const allPost_API = "https://cp-blog.onrender.com/api/post/user"
export const sample_image = "https://marketinginsidergroup.com/wp-content/uploads/2023/09/shutterstock_234456937-scaled-1.jpg"
export const Backgorund_image= "https://lh3.googleusercontent.com/aida-public/AB6AXuB9yybwz4Ta5lROke_QkCfCtWvCBgXQQjVjJJ265P2_L7MqkGtHyWwf_8-vp05rJdBNTrrB18Ex11GxWXPT3-kq2N30KAfWND5ERgEXZPJlJBfcyxgSXdlHk9JpcfD-DhpcDxZ37Ng0N71u9SsDsKWRiS2rtAXmEjSzaIbSM3g1NcZWO96ppHeprMOe4Ly6sldAReZ-ZhAxDt0_xUurerGaOyEPNBxip7RxbXJvgUnB4s4l02PfNYjRfemhPF9kYshBBuE5R1tnbCP6"